### ISSUE TITLE
Demo availability

### ISSUE THREAD

**Issue by vicawil** [DeFacto/DeFacto#29]
Hello, 
I can't find the online demo of DeFacto. The "demo" links on http://defacto.sda.tech/projects/defacto/ and 
http://aksw.org/Projects/DeFacto.html all lead to the github repository. Is it still available?

**Comment by diegoesteves** [comment]
Hello,
happy new year! :-) as soon as we update the demo's link I will get back to you. However, you should be able to deploy on your local machine following instructions available [here](https://github.com/SmartDataAnalytics/DeFacto). 

Please let me know if you have any problems.

**Comment by diegoesteves** [comment]
We are facing some issues due to internal security rules (ports and services). Please use the [docker](https://github.com/DeFacto/DeFacto/tree/master/docker) to run the demo locally. Thanks!
