### ISSUE TITLE
More comprehensive guide to build and deploy on local machine.

### ISSUE THREAD

**Issue by JeeveshN** [DeFacto/DeFacto#30]
It would be really helpful if a more comprehensive guide is provided to deploy Defacto on a local machine if possible command by command (After the installing Maven, Mysql part.).
I have a project and I want to use Defacto as a third party software and am having a lot problem in running it.
Would be really glad if someone could help.

**Comment by mansimarkaur** [comment]
This would be really helpful. @diegoesteves , could you please provide a rough outline of the steps for the same?
Thanks!

**Comment by diegoesteves** [comment]
Hi guys, sure! But first, did you follow the steps in the README file? Can you please describe your error/issue?

**Comment by diegoesteves** [comment]
This should be working over docker: https://github.com/DeFacto/DeFacto/tree/master/docker

As I told before, please send us an error log if you still have problems :-)
